FROM mcr.microsoft.com/dotnet/sdk:8.0-noble

WORKDIR /app

COPY ["Server.csproj", "."]
RUN dotnet restore

COPY . .

RUN dotnet tool install --global dotnet-ef --version 8.*
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update"]